# Generated by Django 2.1.5 on 2019-01-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Enter a new category of tasks!', max_length=20)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter your new task to accomplish!', max_length=20)),
                ('description', models.TextField(blank=True, help_text="If you wanna be verbose about your task, here's your place, go ahead!", max_length=200, null=True)),
                ('schedule_time_to_start', models.DateTimeField(blank=True, help_text='When do you plan to start with this task?', null=True)),
                ('deadline', models.DateTimeField(blank=True, help_text="By when should you finish this task? (Let's all be real and put a realistic deadline!)", null=True)),
                ('priority', models.CharField(blank=True, choices=[('Q1', 'Do First'), ('Q2', 'Schedule'), ('Q3', 'Delegate'), ('Q4', "Don't Do")], default='Q2', help_text='Choose a priority for your task.', max_length=2, null=True)),
                ('hashtag', models.ForeignKey(blank=True, default='general', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.hashtag')),
            ],
            options={
                'ordering': ['deadline', 'schedule_time_to_start'],
            },
        ),
    ]
